# Generated by Django 4.0.6 on 2022-07-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('T', 'Toys'), ('H', 'Home Decor'), ('B', 'Beauty'), ('S', 'Sport Items'), ('O', 'Office Items'), ('O', 'Other')], default='O', max_length=15),
        ),
    ]
